### ISSUE TITLE
バグ：直接入力を有効にしているアプリケーションで英数キー・かなキーが空白として挿入されます。

### ISSUE THREAD

**Issue by 4513ECHO** [mtgto/macSKK#100]
## 概要

直接入力を有効にしているアプリケーションで英数キー・かなキーが空白として挿入されます。
#94 での修正漏れかと思われます。

## 環境

macOS Sonoma 14.2.1
macSKK 0.16.0

**Comment by mtgto** [comment]
再現できました。ご推察の通り #94 で直接入力を考慮に入れていませんでした。対応します。

**Comment by mtgto** [comment]
バグ報告ありがとうございました。
修正して [v0.16.1](https://github.com/mtgto/macSKK/releases/tag/0.16.1) をリリースしました。
