### ISSUE TITLE
要望：変換候補を戻る機能のサポート

### ISSUE THREAD

**Issue by 4513ECHO** [mtgto/macSKK#101]
## 概要

変換モード中で`<Space>`の逆の操作として候補を戻る操作をしたいです。
現状だと変換候補を進みすぎてしまったときは`<C-g>`で最初からやりなおすしかないので少し面倒です。

ddskk・AquaSKKでは`x`にマップされているようです。
参考：https://ddskk.readthedocs.io/ja/latest/05_basic.html#id20

**Comment by mtgto** [comment]
どこにも説明がなくて恐縮ですが、v0.16.0現在ですと `C-p`、矢印の `↑` で一つ前の候補に戻ることができます。
ddskk/AquaSKKの `x` は知らなかったので助かりました。対応しようと思います。

**Comment by 4513ECHO** [comment]
ありがとうございます。ひとまず今ある機能を使いますね。

**Comment by mtgto** [comment]
遅くなりましたが v0.17.0で対応しました。 https://github.com/mtgto/macSKK/releases/tag/0.17.0
