### ISSUE TITLE
要望: 変換候補の一覧表示を出すまでの変換候補送り回数を指定したい

### ISSUE THREAD

**Issue by tsukkee** [mtgto/macSKK#104]
現状、変換してから4回ほどSpaceキーを押した段階ぐらいで一覧表示に切り替わると思うのですが、個人的には初回から一覧表示が出てくれると見通しが立って使いやすいと感じるので、カスタマイズできるようにして頂けると嬉しいです。

**Comment by tsukkee** [comment]
https://github.com/mtgto/macSKK/blob/c90234ea86472d9b029bc4e42fdde99c3fe574de/macSKK/StateMachine.swift#L37-L41
こちらのTODOコメントがまさにこの要望通りでした🙇

**Comment by mtgto** [comment]
要望ありがとうございます。設定できるようにしようと思います。

**Comment by tsukkee** [comment]
ありがとうございます！！

**Comment by mtgto** [comment]
v0.17.0で対応しました。 https://github.com/mtgto/macSKK/releases/tag/0.17.0
既存の変換候補ウィンドウの実装にいろいろ問題があることがわかりいろいろいじったため、もしなにかおかしなところがあれば教えていただけると幸いです🙏

**Comment by tsukkee** [comment]
早速ありがとうございます！！
後ほど試してみます！

**Comment by tsukkee** [comment]
@mtgto 完全に期待どおりでした！ありがとうございます、毎日使います！
