### ISSUE TITLE
バグ: 変換中に`n`が入力されたあとのShift + 子音入力と、Sticky Shift → 子音入力で結果が異なる

### ISSUE THREAD

**Issue by tsukkee** [mtgto/macSKK#108]
# 概要
たとえば、`KanJi`と入力すると「感じ」になりますが、`;kan;ji`だと「兼んじ」となってしまい、`n`が送り仮名側に入ってしまいます。Sticky Shift(`;kan;ji`)でも「感じ」のように`n`が漢字の読みとして解釈されて欲しいです。

# 環境
macOS 13.6.3
macSKK 0.17.0

# 動画
https://github.com/mtgto/macSKK/assets/9748/7a0f7ddd-9fae-400d-9100-bd1247ef48b3

**Comment by mtgto** [comment]
丁寧な再現手順つきの報告ありがとうございます。
これはバグですね。修正します。

**Comment by tsukkee** [comment]
どうもありがとうございます！手元でも修正確認できました。
