### ISSUE TITLE
フルキーボードアクセスをオンにすると変換できなくなる

### ISSUE THREAD

**Issue by pgary3** [mtgto/macSKK#115]
M1 MacBook Air Sonoma 14.3.1、macSKK 0.17.2
アクセシビリティ > キーボード > フルキーボードアクセス をオンにすると、変換ができなくなりました。
ただ、送り仮名付きの場合は変換できました。また再現できないものでしたら、すみません。
よろしくお願いいたします。

**Comment by mtgto** [comment]
ありがとうございます。自分のmacOS 14.3.1環境でも再現しました。
※デフォルトではスペースが「有効にする」に割り当てられているため、まずはそれを別のキーに割り当てたほうがよい。

変換候補のリストが表示されると一瞬リストが表示されてすぐに隠れてしまうためまともに変換ができなくなりますね。

<img width="188" alt="image" src="https://github.com/mtgto/macSKK/assets/1213991/8cc5f85f-2710-4b49-8944-6254cdf11b70">

**Comment by mtgto** [comment]
macOS標準の日本語インプットメソッドだと問題なく操作できるので、なんらか対処方法はありそう?
(NSWindowのLevelかなあ…)

**Comment by mtgto** [comment]
AquaSKKは枠こそ出ないもののフルキーボードアクセスが有効でも変換パネルが表示されるのでそこから調べるのがよさそう。
<img width="578" alt="image" src="https://github.com/mtgto/macSKK/assets/1213991/479c3de2-cda6-4d28-8daa-223eddde12a6">

**Comment by mtgto** [comment]
AquaSKKはマウス操作できないパネルだったので同じような対処はできればしたくなく (面倒なので)
いろいろ試行錯誤してみたところ、アクセシビリティ機能での対象要素としないことでひとまず暫定対処としました。
VoiceOver操作ができなくなるなど副作用もあるため暫定の対処ですが、ひとまず将来考えます。

**Comment by mtgto** [comment]
私の環境ではフルキーボードアクセスが有効になっていると変換候補パネルが出せないのが問題だという認識だったのでとりあえず[v0.18.0](https://github.com/mtgto/macSKK/releases/tag/0.18.0)に暫定対応を入れました。
スペースが使えなくなる問題は環境設定からスペースの割り当てを違うものに変更してみてください。

**Comment by pgary3** [comment]
ご対応いただきありがとうございます。
v0.18.0をインストールし、フルキーボードアクセスからスペースへの割り当てを削除し、変換できるようになりました。
ありがとうございました。

ここに書いたらいけないかもしれませんが、PowerPointの場合、Ctrl+Jが両端揃えに割り当てられているのをPowerPoint側で変更できないので、Karabiner-Elements使うしかないでしょうか。

**Comment by mtgto** [comment]
@pgary3 

> ここに書いたらいけないかもしれませんが、PowerPointの場合、Ctrl+Jが両端揃えに割り当てられているのをPowerPoint側で変更できないので、Karabiner-Elements使うしかないでしょうか。

私はPowerPointを入れていないので推測でしかないですが、AquaSKKでもPowerPointでCtrl-Jが使えないという情報が検索すると出てくるのでmacSKKのCtrl-JがPowerPointで使えないとしたらAquaSKKと同じ原因だと思われます。

Karabiner-Elementsを入れて「PowerPointアプリでCtrl-Jを打った場合はかなキーのようにふるまう」という設定をComplex Modificationsに入れればかな変換にすることは可能だろうとは思います。

いつごろに、とお約束はできないですが、私のほうでKarabiner-Elementsユーザー向けにCtrl-Jをかなキーのようにふるまうルールの配布はしようと思っています。
また、こちらもお約束はできないですがCtrl-Jを使えないアプリ向けにmacSKKで「このアプリではこのキーバインドをCtrl-Jのかわりに利用する設定」ができるようにしようかなと考えています。

**Comment by pgary3** [comment]
Issueとずれた質問にもお答えいただきありがとうございます。
Karabiner-Elementsを使用すればよいのでしょうが、
AquaSKKを使っている時から、PowerPointでは切り替えをcommand+spaceで行うようにしています。
将来的に対応が可能なようであれば嬉しいです。
