### ISSUE TITLE
一部のアプリケーションで英字モード/カタカナモードなどに切りかえる際に `l` や `q` が入力される

### ISSUE THREAD

**Issue by gw31415** [mtgto/macSKK#119]
便利に使用させていただいております。

KittyやLINE、weztermなど一部のアプリケーションでは、入力モードを切りかえる際入力に用いていたLキーやQキーの文字がそのまま入力されてしまうことがあります。

参考までに、AquaSKKだと空文字挿入などを行うことで対応しているようです。
https://github.com/codefirst/aquaskk/wiki/Workaround

**Comment by mtgto** [comment]
試してみたのですが、自分の環境ではKittyとLINEはAquaSKKでもmacSKKでも同じようにLやQがそのまま入力されてしまいました。
@gw31415 さんの環境ではAquaSKKの互換性機能で対応されているのでしょうか。もう少し情報をいただければありがたいです。KittyはもしかしたらKitty自体の設定が必要だったりするのかしら…?

### 検証した環境

- macOS 14.3.1 (Apple Silicon)
- macSKK 0.18.0
- AquaSKK 4.7.3
- Kitty 0.32.2
- LINE 8.6.0.3277 (Mac App Store)
- Wezterm 20240203-110809-5046fc22
  - [macos_forward_to_ime_modifier_mask](https://wezfurlong.org/wezterm/config/lua/config/macos_forward_to_ime_modifier_mask.html) に `SHIFT|CTRL` を設定しています
  - https://github.com/mtgto/macSKK?tab=readme-ov-file#q-wezterm-%E3%81%A7-c-j-%E3%82%92%E6%8A%BC%E3%81%99%E3%81%A8%E6%94%B9%E8%A1%8C%E3%81%95%E3%82%8C%E3%81%A6%E3%81%97%E3%81%BE%E3%81%84%E3%81%BE%E3%81%99
- Karabiner ElementsのComplex Modificationsは未使用

## AquaSKKの互換性モードを使用しない場合

### Kitty

操作 | 期待される動作 | macSKK | AquaSKK
--- | --- | --- | ---
かなモードでlキーを入力 | 英数モードに切り替わり何も入力されない | 🙅 英数モードに切り替わるがlが入力される | 🙅 英数モードに切り替わりlが入力される
かなモードでqキーを入力 | カナモードに切り替わり何も入力されない | 🙅 カナモードに切り替わるがqが入力される | 🙅 カナモードに切り替わるがqが入力される
英数モードでC-jを入力 | かなモードに切り替わり何も入力されない | 🙅 かなモードに切り替わるが改行される | 🙅 かなモードに切り替わるが改行される

### LINE

操作 | 期待される動作 | macSKK | AquaSKK
--- | --- | --- | ---
かなモードでlキーを入力 | 英数モードに切り替わり何も入力されない | 🙅 英数モードに切り替わるがlが入力される | 🙅 英数モードに切り替わりlが入力される
かなモードでqキーを入力 | カナモードに切り替わり何も入力されない | 🙅 カナモードに切り替わるがqが入力される | 🙅 カナモードに切り替わるがqが入力される
英数モードでC-jを入力 | かなモードに切り替わり何も入力されない | 🙆 かなモードに切り替わり何も入力されない | 🙆 かなモードに切り替わり何も入力されない

### Wezterm

操作 | 期待される動作 | macSKK | AquaSKK
--- | --- | --- | ---
かなモードでlキーを入力 | 英数モードに切り替わり何も入力されない | 🙆 英数モードに切り替わり何も入力されない | 🙆 英数モードに切り替わり何も入力されない
かなモードでqキーを入力 | カナモードに切り替わり何も入力されない | 🙆 カナモードに切り替わり何も入力されない | 🙆 カナモードに切り替わり何も入力されない
英数モードでC-jを入力 | かなモードに切り替わり何も入力されない | 🙆 かなモードに切り替わり何も入力されない | 🙆 かなモードに切り替わり何も入力されない

### まとめ

- macSKKもAquaSKKも変わらず、KittyとLINEではq/l入力で文字が入力されてしまう
- Weztermは特に問題なさそう?

## AquaSKKの互換性モードを使用する場合

### Kitty

https://zenn.dev/tsukkee/articles/stmk_advent_calendar_vim#%E3%82%BF%E3%83%BC%E3%83%9F%E3%83%8A%E3%83%AB を参考に空文字挿入を有効にしてみましたが、自分の環境では特に変わりませんでした。なにが違うんでしょうか…

操作 | 期待される動作 | AquaSKK | AquaSKK (互換性機能を使用)
--- | --- | --- | ---
かなモードでlキーを入力 | 英数モードに切り替わり何も入力されない | 🙅 英数モードに切り替わるがlが入力される | 🙅 英数モードに切り替わりlが入力される
かなモードでqキーを入力 | カナモードに切り替わり何も入力されない | 🙅 カナモードに切り替わるがqが入力される | 🙅 カナモードに切り替わるがqが入力される
英数モードでC-jを入力 | かなモードに切り替わり何も入力されない | 🙅 かなモードに切り替わるが改行される | 🙅 かなモードに切り替わるが改行される

### LINE

元から露払後確定が有効になっていましたが、今回のテスト項目では特に変化がないようでした。

**Comment by mtgto** [comment]
Kittyについて、AquaSKKの空文字挿入と同じ処理をしてみたところ

- C-jによるかな入力への切り替え
- qによるカナ入力への切り替え
- lによる英数入力への切り替え

いずれについても改行されたりqやlが入力されることがなくなりました。

AquaSKKの空文字挿入を有効にした場合の実際の挙動は、"\f" (0x0c) をsetMarkedTextして空文字列をsetMarkedTextしている。
https://github.com/codefirst/aquaskk/blob/4.7.5/platform/mac/src/server/SKKInputController.mm#L405-L412

**Comment by gw31415** [comment]
お返事遅れました！気づかず申し訳ございません。
そうですね、空文字挿入の処理を有効にすると挿入されることがなくなります。

**Comment by gw31415** [comment]
今更で本当に申し訳ありませんがこのような設定になっています。

<img width="592" alt="image" src="https://github.com/mtgto/macSKK/assets/24710985/c6f2ef28-a90e-4d6c-b426-c49798e65409">

**Comment by mtgto** [comment]
@gw31415 お返事ありがとうございます。Weztermについては @gw31415 さんの環境では問題は起きてないということでよろしいでしょうか?

私の環境でもMacを再起動したらAquaSKKの互換性が反映されたようでKittyとLINEについては空文字挿入を有効にしたら問題が起きなくなりました。
https://github.com/mtgto/macSKK/issues/119#issuecomment-1959656933 の表を書き直します。

**Comment by gw31415** [comment]
すみません、Weztermを一時的にインストールしていたものでスクショ以前に設定をクリアしたのでこうなっています。
おそらく、macos_forward_to_ime_modifier_mask周辺の設定を弄っている間に混乱してしまったんだと思います。
お騒がせしました 🙇

**Comment by mtgto** [comment]
Alacritty v0.13.1でも同様にq/l/C-jが入力される問題が空文字挿入で問題が起きなくなるのを確認。 #132
VSCodeのターミナル画面でも起きることを確認。ただVSCodeのBundle Identifierを固定で適用するかはちょっと迷ったので後回し。
おそらくmacSKKで得られる情報では今フォーカスを持っているのがVSCodeなのはBundle Identiferからわかってもターミナルなのかエディタなのかはわからない気がする…?

**Comment by mtgto** [comment]
v0.19.0でKitty, LINE, Alacrittyのときにモード変更時に空文字挿入するワークアラウンドを入れて対応しました。
https://github.com/mtgto/macSKK/releases/tag/0.19.0

今後利用者がアプリケーションごとに設定できるようにするまでこのIssueはOpenにしておきます。

**Comment by mtgto** [comment]
#135 で利用者がアプリごとに設定可能 (今のところ空文字挿入だけ) できるようにしました。
v0.20.0から設定できます。 https://github.com/mtgto/macSKK/releases/tag/0.20.0
