### ISSUE TITLE
送り仮名を含む候補の新規登録後の確定で送り仮名が再現されない

### ISSUE THREAD

**Issue by gw31415** [mtgto/macSKK#136]
スクリーンショットの通り、送り仮名を含む語句を新規登録し確定すると送り仮名部分が入力前から消えてしまいます。

1. <img width="179" alt="image" src="https://github.com/mtgto/macSKK/assets/24710985/4a30076a-0261-46d8-8ad9-3a749676009b">

2. <img width="130" alt="image" src="https://github.com/mtgto/macSKK/assets/24710985/f9258def-f3c1-4e98-bb0b-05678dc71223"> (「紐付け」が残る想定)

**Comment by mtgto** [comment]
報告ありがとうございます。再現できました。
修正しようと思います。

**Comment by mtgto** [comment]
v0.20.0で対応しました。
https://github.com/mtgto/macSKK/releases/tag/0.20.0
