### ISSUE TITLE
機能のマッピングを設定できるようにする

### ISSUE THREAD

**Issue by uga-rosa** [mtgto/macSKK#148]
開発ありがとうございます！
最近macを使い始めたので、これを常用しています。

さて本題ですが、現状 `;` や `l` などの特殊な機能のキーが固定されています。
しかし私はazikの仮名テーブルを使っているので、一部のキーが競合してしまいます。
調整できるようにしてもらえませんか？

よろしくお願いします。

**Comment by mtgto** [comment]
機能要望ありがとうございます。
現状セミコロンやlなどをソースコードで固定でもっているため、その処理を設定変更にする必要があるためそこそこ時間がかかりそうですがAquaSKKでもできていましたし対応しようと思います。

**Comment by uga-rosa** [comment]
ありがとうございます！
ぜひよろしくお願いします 🙇‍♂️

**Comment by mtgto** [comment]
@uga-rosa かなり時間がかかってしまいましたがv0.26.0でキーバインドの設定機能を入れました。
私はazikを使ってないため、azikを併用できるのかよくわかっていないところも多いので、なにか気になるところなどあればこのIssueや別Issueで教えていただけると助かります 🙏 
https://github.com/mtgto/macSKK/releases/tag/0.26.0

**Comment by uga-rosa** [comment]
ありがとうございます！
「la」で「ぁ」などの変換が干渉していたのですが、これで今まで通り使えるようになります。助かります～～～
