### ISSUE TITLE
漢字変換候補ラベルのバリエーション

### ISSUE THREAD

**Issue by pelopor-pelopor** [mtgto/macSKK#157]
MacでのSKK開発、ありがたく使用させていただいております。
現在は、漢字変換候補ラベルが"1, 2, 3..."に固定されています。これをEmacs上のddskkの標準設定（skk-henkan-show-candidates-keys）に合わせて、"a,s,d,f..." なども選択できるようにしていただけると有り難いです。
ご検討くださいますようお願いいたします。

**Comment by mtgto** [comment]
要望ありがとうございます。
数字形式もしくはQwertyでのASDFGHJKLの2択で対応してみようと思います。
(Dvorakなどを使ってる人など選択肢をカスタマイズできてもいいかもしれないですがあまり需要もなさそうな気がするのでとりあえず実装が簡単な設定画面で選択する形式の予定)

**Comment by pelopor-pelopor** [comment]
ありがとうございます。期待しております。

**Comment by mtgto** [comment]
Dvorakは "aoeuidhtn" にしておくとよさそう (左手用・右手用はいったん置いておく)。
https://ja.wikipedia.org/wiki/Dvorak%E9%85%8D%E5%88%97

**Comment by mtgto** [comment]
v0.23.0でASDFGHJKLを選択可能にしました。
https://github.com/mtgto/macSKK/releases/tag/0.23.0

**Comment by pelopor-pelopor** [comment]
ありがとうございました!
