### ISSUE TITLE
新規候補登録中にさらに新規候補登録しようとしても現在の新規候補登録画面のままになる

### ISSUE THREAD

**Issue by gw31415** [mtgto/macSKK#158]
# 概要
候補Aの新規登録中に、候補A中の部分語句Bを新規登録する必要が出てきた場合、候補Bの登録画面に移動することができません。
登録状態のネストが上手くいっていないようです。

# 詳細
1. 新規候補登録中の画面です。この状態で<kbd>Space</kbd>を押下します。
  <img width="257" alt="image" src="https://github.com/mtgto/macSKK/assets/24710985/e1bde64b-9cec-4f3e-bfec-4f61ab1abd3b">

2. `[登録：かいせんし]` に移動してほしいところ、「▽かいせんし」入力前の状態に戻ります。
<img width="185" alt="image" src="https://github.com/mtgto/macSKK/assets/24710985/18b1d21c-531e-4d2e-9b0e-4f2f2c7d5193">

**Comment by mtgto** [comment]
報告ありがとうございます。なるほど、単語登録中に単語登録はできてもよさそうですね。
いまやっているキーバインド設定が終わったら対応しようと思います。

**Comment by gw31415** [comment]
なるほど、仕様だったのですね。
検討ありがとうございます！

**Comment by mtgto** [comment]
仕様というわけではなく、入れ子で単語登録できてもいいことに気付いてなかったので実装してなかっただけです🙇

**Comment by mtgto** [comment]
v0.24.0で対応しました。 https://github.com/mtgto/macSKK/releases/tag/0.24.0
