### ISSUE TITLE
v0.23.0でQwerty配列以外の配列を設定で選ぶとlやqなどが機能しない

### ISSUE THREAD

**Issue by mtgto** [mtgto/macSKK#164]
#159 でC-jやqやlなど、SKKの操作用のキーをキーコードで判定するように変更しました。
ですが、macSKKのキー配列変更でQwerty以外を選ぶと前述のキーで操作できなくなることがわかりました。

これはmacSKK設定でのキー配列の変更のようにソフトウェア的なキー配列の変更をしても、キーを押したときのキーコードはQwertyのときと変わらないということに気付かなかったことによるバグです。
例えばAキーを押したときにkeyCodeは1、Sキーを押したときにkeyCodeは2となります。
設定でDvorakを選んでいた場合、Sと印字されているキーを押したときに入力されるのは "O" ですが、keyCodeは2のままになっています。

設定で非Qwerty配列を使っていてv0.23.0に上げてしまった方はひとまずv0.22.2をご使用ください。
https://github.com/mtgto/macSKK/releases/tag/0.22.2

このバグの修正後、v0.23.1としてリリースする予定です。

**Comment by pgary3** [comment]
新しいissueにすべきかとも思ったのですが、関連していそうなのでこちらにcommentします。
v0.23.0だと、標準のメモやCotEditorでshift押しながら矢印キーで文字列を選択しようとしても画面上のカーソルが動きません。設定はQwerty配列です。
Microsoft Wordだとshift押しながら矢印キーで文字列が選択できます。
また、v0.22.2にすると、shift押しながら矢印キーで文字列が選択できるようになりました。
再度、v0.23.0とv0.22.2にするのを繰り返してみましたが、やはり同じ動作でした。

**Comment by mtgto** [comment]
@pgary3 ありがとうございます。v0.23.0に入れた変更が原因ですね。
シフトキーを押しながらでも機能してほしいキーがあることが漏れておりました。コメント報告ありがとうございます。

**Comment by mtgto** [comment]
v0.23.1 https://github.com/mtgto/macSKK/releases/tag/0.23.1 で修正しました。
