### ISSUE TITLE
LibreOfficeで fn + delete キー が効かない

### ISSUE THREAD

**Issue by pelopor-pelopor** [mtgto/macSKK#176]
MacSKKの問題か、十分に切り分けができていないのですが、報告いたします。
LibreOffice Writerで、"fn"キー + "delete"キー（Windowsにおけるdelete）が効きません。
・OS標準の英語入力および日本語入力、AquaSKKでは効きます。

**Comment by mtgto** [comment]
報告ありがとうございます。
v0.23.0以降で行った誤った作業により、Fn + Deleteキー (カーソル右側の文字を消す機能) がたしかに無視されるようになっていました。
次のバージョンで修正予定です。

**Comment by mtgto** [comment]
v0.24.1で対応しました。
https://github.com/mtgto/macSKK/releases/tag/0.24.1
