### ISSUE TITLE
非ユーザー辞書におけるブラケット記号の扱い

### ISSUE THREAD

**Issue by fabon-f** [mtgto/macSKK#183]
利用しているSKK辞書に`[`や`]`を含むエントリが含まれていた場合、その行が正しく読み込めずスキップされてしまいます。

```
; 例
あれきさんどろす /[Alexandros]/
```

送りなしエントリの場合は`[]`をただの記号として扱う(ブロック形式としてパースしない)ことで問題を解決できそうです。
(記号を含むエントリは事実上100%固有名詞、すなわち送りなしエントリなのでこれでOKのはず)

**Comment by mtgto** [comment]
報告ありがとうございます。
提案通り、 `送りなしエントリの場合は[]をただの記号として扱う` がよさそうですね。

**Comment by mtgto** [comment]
0.25.1で修正しました。
https://github.com/mtgto/macSKK/releases/tag/0.25.1
