### ISSUE TITLE
スラッシュやセミコロンを含む単語の扱い

### ISSUE THREAD

**Issue by fabon-f** [mtgto/macSKK#184]
# 辞書読み込み時

`(concat ...)`を使ってエスケープされている(主に非ユーザー辞書の)エントリにおいて、`\057`は適切に`/`に変換されるものの、`\073`は`;`にならずそのまま出力されてしまいます。

# ユーザー辞書登録時

スラッシュやセミコロンを含む単語を辞書登録するか既存の辞書から変換し、その後ユーザー辞書を保存すると、スラッシュやセミコロンがエスケープされない状態でファイルに保存され、次に変換したときに意図しない候補が出てしまいます。

たとえば「ふぇいとぜろ」に対し「Fate/Zero」と変換してユーザー辞書を保存すると、`ふぇいとぜろ /Fate/Zero/`というエントリが追加され、次に変換した際に「Fate」と「Zero」という正しくない候補が出てしまいます。「STEINS;GATE」の場合も保存されるエントリが`しゅたいんずげーと /STEINS;GATE/`となるので同様の問題が発生します。

**Comment by mtgto** [comment]
報告ありがとうございます。

`\073` はSKK-JISYO.Lにはなかったため気付いていませんでした。対応します。

ユーザー辞書登録時にスラッシュやセミコロンのような辞書用に使われている特殊文字が含む場合も同様の対応をしたほうがよさそうですね。対応します。

**Comment by mtgto** [comment]
0.25.1で修正しました。
https://github.com/mtgto/macSKK/releases/tag/0.25.1
