### ISSUE TITLE
要望: 「変換中のEnterキーで確定+改行」設定

### ISSUE THREAD

**Issue by fabon-f** [mtgto/macSKK#189]
SKKには伝統的に「変換中にEnterキーを押すと確定した上でEnterキーが送出される」設定があります(AquaSKKだと「Enter による確定で改行しない」をオフにした場合に相当)。macSKKにも類似機能があると嬉しいです。

https://tomoya.hatenadiary.org/entry/20101212/1292089972

(SKKの伝統的には「確定+改行」の方がデフォルトのようですが、他IMEや過去バージョンとの互換性を考えると現状の動作を維持した方が良さそうです)

**Comment by mtgto** [comment]
要望ありがとうございます。私はddskkなど他のSKKを使う前にAquaSKKを使ってたんですが、「Enter による確定で改行しない」をオンにしておりこの設定ってなんのためにあるんだろう…? くらいしか思っていませんでした。
AquaSKKでこの設定をオフにしていた方もいると思いますし対応しようと思います。

**Comment by mtgto** [comment]
v0.27.0で対応しました。設定画面から変更可能です。
デフォルトはこれまでと同じ「Enterでは確定だけで改行はしない」ほうにしてあります。
https://github.com/mtgto/macSKK/releases/tag/0.27.0
