### ISSUE TITLE
macSKKのABC（英語モード）でIdeaVimのVisual modeが壊れる

### ISSUE THREAD

**Issue by uga-rosa** [mtgto/macSKK#198]
このように壊れます。
入力の取り方が特殊なんですかね？

mac標準の英語ソースを使うようにすれば回避できたので、緊急度は低いです。

https://youtrack.jetbrains.com/issue/VIM-3585/When-I-press-any-key-in-visual-mode-the-text-under-the-cursor-deleted.

**Comment by uga-rosa** [comment]
すいません、READMEに書いてましたね。
既に認識されてるならこのissueは閉じておいたほうがいいでしょうか？

**Comment by mtgto** [comment]
@uga-rosa 報告ありがとうございます。

> Java AWT製アプリケーションで入力ができない問題のワークアラウンド対応 (JetBrain製品など)

READMEに書いてあるというのはおそらく↑のことですよね。
これはC-jやqがうまく動かないという事例なので、IdeaVimでのvキーのことは把握していませんでした。

macOS標準の英語ソース以外でもAquaSKKのASCIIでもIdeaVim + vキーは問題ないようだったのでmacSKK側の問題と思われます。
JetBrainsのIssueについてはmacSKKで発生したのであればmacSKKの問題として閉じることをおすすめいたします 🙏

**Comment by uga-rosa** [comment]
なるほど、別件でしたか。それなら報告してよかったです笑

visual mode中にどんなキーを打ってもバッファの文字が消されるので、結構根本的なところに原因があるかもしれません…

**Comment by mtgto** [comment]
IntelliJ IDEA特有でIdeaVimのビジュアルモードがうまく動かない問題があったためv1.0.1で修正しました。
https://github.com/mtgto/macSKK/releases/tag/1.0.1
