### ISSUE TITLE
入力ソース名がREADMEと異なっている

### ISSUE THREAD

**Issue by osak** [mtgto/macSKK#211]
インストール後のセットアップについて、READMEには

> macSKKのインストール後に、システム設定→キーボード→入力ソースから「ひらがな (macSKK)」と「ABC (macSKK)」を追加してください。

と書かれていますが、実際には (macSKK) が名前に含まれていないようです（添付画像）。アイコンでSKKだと分からなくはないものの、気づくまでにちょっと時間がかかりました。
<img width="560" alt="スクリーンショット 2024-09-01 17 47 47" src="https://github.com/user-attachments/assets/4ea89c43-106c-4d9d-a9f1-9717c3baa1ed">

**Comment by mtgto** [comment]
報告ありがとうございます。
v1.0.0 (#193) で、以前の "ひらがな (macSKK)" 形式から "ひらがな" 形式に変更したんですがREADMEの修正を忘れていました。

**Comment by mtgto** [comment]
v1.2.0で修正しました。報告ありがとうございました。
https://github.com/mtgto/macSKK/releases/tag/1.2.0
