### ISSUE TITLE
変換中のBackspaceを、変換候補を確定してからの文字削除として使いたい

### ISSUE THREAD

**Issue by atusy** [mtgto/macSKK#215]
macSKKの `Backspace` は実質 `^G` 相当なので機能がかぶってます。
SKK日本語入力FEPやlibskk、skkeletonなどのように、 `Backspace` すると確定してから文字削除する挙動を利用したいです。

- macSkk
    - `▼食べ`でバックスペースすると `▽た*べ`になる
- libskkなど
    - `▼食べ`でバックスペースすると `食`になる

**Comment by mtgto** [comment]
ありがとうございます。私はAquaSKKしかまともにSKK入力を経験してないためそれに合わせてmacSKKのバックスペースを実装していました。
挙げていただいたFEP, libskk, skkeleton以外にもddskkもBackspaceで確定するようなのでそちらに合わせる方針で検討してみます。

**Comment by mtgto** [comment]
ddskkでは変換候補リストが表示されているときはBackspaceは前ページへの遷移として機能するようです。
skkeletonでも試してみてどっちに合わせるかを検討します。

**Comment by mtgto** [comment]
> skkeletonでも試してみてどっちに合わせるかを検討します。

skkeletonではddskkと異なり変換候補リスト表示中もBackspaceで一文字後退して確定しているようでした。
どっちがいいのかわからないのですが、ひとまずページ戻りとしてみます。

**Comment by atusy** [comment]
ありがとうございます。今手元にデバイスがないのですが、ページ戻りはページ戻りでキーありませんでしたっけ？あるなら機能を分ける意味で、バックスペースは確定後削除に集中したほうがよさそうに思います。

**Comment by mtgto** [comment]
> ページ戻りはページ戻りでキーありませんでしたっけ？

これはmacSKKでのはなしでしょうかね。
例えばあまりメジャーなキーではないかもですがPageUpキーを割り当てるのはありかもですね。
(いまはPageUpは無視してました)

どっちが便利か自分もあまり自信がないのですが、変換候補リストのありなしで変わるより確定後削除に統一しておくほうがはたしかに自然な気もするのでそっちにしようかなと思います。

**Comment by mtgto** [comment]
AquaSKKは設定になっていました。有効にしたときに確定するのはインライン変換のときだけのようでした。

<img width="480" alt="image" src="https://github.com/user-attachments/assets/afb218a1-e42d-4871-8f1d-f9e0027dd0c7">

**Comment by mtgto** [comment]
迷うくらいなら設定にしてしまおうと思い、v1.2.0現在の挙動も含む3つの挙動を選択可能にすることにしました。

**Comment by atusy** [comment]
レスポンスできてなくてすみません。設定可能なのありがたいです！

**Comment by mtgto** [comment]
v1.3.0で設定できるようにしました。
https://github.com/mtgto/macSKK/releases/tag/1.3.0
