### ISSUE TITLE
Bug: 空のエントリー 「foo //」や無効なエントリーなどがあるとパースに失敗してIMEごと落ちる

### ISSUE THREAD

**Issue by LumaKernel** [mtgto/macSKK#233]
https://github.com/tani/skk-jisyo-latex/blob/master/SKK-JISYO.latex.utf8 を読み込もうとしたら、次のような行を無効化しないと読み込めず、また、単に「Parse Error」と安全にエラーになる場合もあれば、IMEごと落ちるケースもありました。
IMEごと落ちた場合は、IMEの一覧から一度削除し、再度登録する、といったことをすれば正常に再起動してくれました。

```
;; 略
mathslash ///
;; 略
semicolon /;/
;; 略
lbrack /[/
;; 略
bullet //
smblkcircle //
;; 略
blockuphalf //
```

macSKKで動かないものをコメントアウトした完全版がこちらに一応あります: https://github.com/LumaKernel/dotfiles/blob/master/skk-dict/SKK-JISYO.latex.utf8.txt

**Comment by LumaKernel** [comment]
すみません、これはちょっとだけ古いバージョンでやりました。またのちほど最新バージョンでも確認してみます…。

**Comment by mtgto** [comment]
v1.4.0でクラッシュする問題とエラーだと言われてしまう問題に対応しました。
v1.4.0では空文字列への変換候補は存在しないものとしていますが、今後問題ないことが確認できたら空文字列への変換にも対応する予定です。
問題の報告いただきありがとうございました。
https://github.com/mtgto/macSKK/releases/tag/1.4.0
