### ISSUE TITLE
Feature Request: 辞書のシンボリックリンクへの対応

### ISSUE THREAD

**Issue by LumaKernel** [mtgto/macSKK#234]
Dictionaries配下の辞書がシンボリックリンクにも対応しているとありがたいなと思っています。現状は設定の一覧に出てこない仕様かと思います。

`sym-test.txt` を辞書として適当に用意し、

```sh
sudo ln -sf sym-test.txt "$HOME"/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries/sym-test.txt
```

を実行することで検証可能です。

## バージョン情報

- macSKK: 1.3.1
- macOS: 14.5 (23F79)
- Chip: Apple M1 Pro

**Comment by mtgto** [comment]
申し訳ありません、シンボリックリンクの対応は今のところ予定しておりません。
これはmacOSのサンドボックス機能を有効にしたアプリケーションでは `~/Library/Containers/net.mtgto.inputmethod.macSKK/Data` 以外の場所の読み込みには許可を与える必要があるためです。
https://github.com/mtgto/macSKK/issues/92#issuecomment-1886875190

ただシンボリックリンクからの読み込みへの要望はこれで2回目なので「ユーザーが明示的に選択することでApp Sandbox外の辞書ファイルを読むようにする」ことを検討しようと思います。

自分用メモ: サンドボックスが有効なアプリであっても、オープンダイアログからユーザーが明示的にファイルを開くことで、そのファイルへのアクセス権を取得することができる。
ファイルじゃなくとも許可したフォルダ内のファイルならおそらく参照可能にできるはず。
https://developer.apple.com/documentation/security/accessing-files-from-the-macos-app-sandbox#Access-files-with-standard-user-interactions

**Comment by LumaKernel** [comment]
なるほどです！丁寧にご説明いただきありがとうございます……！ ❤️
