### ISSUE TITLE
Feature Request: .utf8 や .utf8.txt 等の拡張子の場合はデフォルトの選択肢をUTF8にする機能

### ISSUE THREAD

**Issue by LumaKernel** [mtgto/macSKK#235]
タイトルの通り、拡張子等によりデフォルトで選択されているエンコーディング ( i アイコンから指定できるもの ) が指定できると嬉しいなと思いました。

## バージョン情報

- macSKK: 1.3.1
- macOS: 14.5 (23F79)
- Chip: Apple M1 Pro

**Comment by mtgto** [comment]
報告ありがとうございます。これはそう難しくないはずなので対応します。

**Comment by mtgto** [comment]
v1.4.1で「`utf8` がファイル名のどこかに入っていればEUC-JPではなくUTF-8としておく」ようにしました。
https://github.com/mtgto/macSKK/releases/tag/1.4.1
