### ISSUE TITLE
句読点で"，" "．"を選択可能にする

### ISSUE THREAD

**Issue by HALQME** [mtgto/macSKK#247]
かわせみの設定画面から引用させていただきます。
以下のように、句読点としてカンマやピリオドを利用できるように対応いただけたらと思います。
<img width="577" alt="image" src="https://github.com/user-attachments/assets/a3ac152b-dbaa-46df-b152-d01abf55f000">

**Comment by mtgto** [comment]
GUIからは設定できないのですが、現在の最新バージョンv1.4.1であれば「ローマ字変換ルールの変更」によって設定することが可能です。

https://github.com/mtgto/macSKK?tab=readme-ov-file#%E3%83%AD%E3%83%BC%E3%83%9E%E5%AD%97%E5%A4%89%E6%8F%9B%E3%83%AB%E3%83%BC%E3%83%AB%E3%81%AE%E5%A4%89%E6%9B%B4

kana-rule.confを `~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Settings/kana-rule.conf` に配置後、 `&comma;` と `.` の既存の割り当てを行頭に`#`を入れて無効にした上で全角のカンマとピリオドを割り当てることで可能かと思います。

https://gist.github.com/mtgto/b55dc47437793611f810dc01e02b24cc#file-kana-rule-conf-L238-L239
のファイルを配置して試していただけないでしょうか．

**Comment by HALQME** [comment]
ありがとうございます!!!
ちなみに文書の種類でコンマと句点の使い分けが激しいのですが、すばやく変更する方法はファイルの編集しかないでしょうか……

**Comment by mtgto** [comment]
残念ながらv1.4.1現在では設定画面での設定のようなものは用意していないのでkana-rule.confファイルでのみ設定できます。

文書の種類で切り換えたいという要望は例えば設定画面で設定できればだいぶマシになるのでしょうか?
例えばkana-rule.confファイルの設定を上書きするようなカンマ・ピリオドの入力を設定画面で設定できるようにすることは実装することはできそうです。

他に思いついたパターン

- 入力メニューで選択できるようにする (要実装)
  - メニューバーから「カンマ・ピリオドの入力を設定で上書きする」を選択することで上書きの有効・無効を切り換えられる
- 普段使ってないキーを全角のカンマ・ピリオドに割り当てる
  - たとえば `z,` はデフォルトでは「‥」、`z.` は「…」に割り当てていますが、これを全角カンマとピリオドに割り当てることも可能です。

**Comment by HALQME** [comment]
> 文書の種類で切り換えたいという要望は例えば設定画面で設定できればだいぶマシになるのでしょうか?

はい! macOS日本語入力やかわせみなどではGUIからわりと簡単に切り替えが出来るようにされているので（そもそも正規の設定方法としてはGUIしか提供されていない?）ある程度の需要はあるのではないか，と愚推しますが開発者様の優先度の範囲で扱っていただければと思います。
わたし個人としては `z,` / `z.` への割り当てで一旦は対処できそうですので，こちらを利用させていただくつもりです。
ありがとうございます。<m(__)m>

**Comment by mtgto** [comment]
v1.5.0で設定から変更できるようにしました。
https://github.com/mtgto/macSKK/releases/tag/1.5.0

**Comment by HALQME** [comment]
捗ります!!! ありがとうございました!!
