### ISSUE TITLE
プライベートモードを永続化するための設定

### ISSUE THREAD

**Issue by s3igo** [mtgto/macSKK#251]
現状、プライベートモードは本体の再起動によりリセットされます。
一時的に辞書への登録を無効化したいときに便利な機能ですが、#250 に関連して、常に辞書に登録したくないケースのためにプライベートモード永続化する設定を追加していただけるとありがたいです。

**Comment by mtgto** [comment]
Issueありがとうございます。ご指摘のとおり、本体の再起動によってプライベートモードはリセットされます。
(macSKKプロセスの再起動でもリセットされます)
たしかに設定として永続化してしまうのがよさそうなので対応しようと思います。

**Comment by mtgto** [comment]
v1.6.0で対応しました。 https://github.com/mtgto/macSKK/releases/tag/1.6.0
