### ISSUE TITLE
バグ：英数・かなキーを打つと空白が挿入される

### ISSUE THREAD

**Issue by 4513ECHO** [mtgto/macSKK#91]
## 概要

任意の入力欄にフォーカスが当たっている状態で英数キー・かなキーを打つと空白（`U+0020`）が挿入されてしまいます。

## 環境

macOS Sonoma 14.2.1 
macSKK 0.15.0

## 動画

https://github.com/mtgto/macSKK/assets/81011153/22011cf6-2557-4888-95f3-5003d0f69844

**Comment by mtgto** [comment]
[v0.15.1](https://github.com/mtgto/macSKK/releases/tag/0.15.1)で対応しました。

**Comment by 4513ECHO** [comment]
ありがとうございます！
