### ISSUE TITLE
要望: シンボリックリンクのSKK辞書サポート

### ISSUE THREAD

**Issue by peacock0803sz** [mtgto/macSKK#92]
SKK辞書をNeovimプラグインとしてGItHubから取得し管理しているため、`~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries` 配下にシンボリックリンク形式で辞書を配置したいです

**Comment by mtgto** [comment]
`~/Library/Containers/net.mtgto.inputmethod.macSKK/Data` はサンドボックス化したmacOSアプリの隔離されたファイルを配置するためのフォルダ (App Container) なので、サンドボックス外へのシンボリックリンクを置いても読むことができません。

現状の実装ではシンボリックリンクは辞書一覧にも表示されないように弾いています。
https://github.com/mtgto/macSKK/blob/0.15.0/macSKK/UserDict.swift#L324-L326
試しに `URL#isRegularFile` かどうかを見ている条件分岐を外して有効な辞書として読み込もうとするとApp Sandbox侵害により次のようなエラーが発生します。

```
SKK辞書 SKK-JISYO.test.utf8 の読み込みに失敗しました!: Error Domain=NSCocoaErrorDomain Code=257 "ファイル“SKK-JISYO.test.utf8”を表示するためのアクセス権がないため、開けませんでした。" UserInfo={NSFilePath=/Users/username/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries/SKK-JISYO.test.utf8, NSUnderlyingError=0x600001e28240 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

Neovimプラグイン側で macSKKのコンテナフォルダ内 (`~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries`) に辞書ファイルを置いたり、macSKKのコンテナフォルダに辞書ファイルを置きそちらからneovimの辞書フォルダ? のような場所にシンボリックリンクを作るのは難しいでしょうか?

**Comment by peacock0803sz** [comment]
ありがとうございます。プラグイン側でシンボリックリンクを作成する処理できそうです。
