### ISSUE TITLE
要望: 仮名テーブルのカスタマイズについて

### ISSUE THREAD

**Issue by 4513ECHO** [mtgto/macSKK#93]
## 概要

AquaSKKのように仮名テーブル （rule file）を自由に弄れるようにしてほしい。

## ユースケース

1. 約物

 現在は`!?()`などの約物は半角になっていますが、ユーザが全角にすることもできるようになります。
また、`z+{任意のキー}`で約物を打つ機能も自由に拡張したいです。

2. ゔ

`vu`と打つと「う゛」になりますが、これを 「ゔ」に置き換えられるようになります。
ただし、これを実現するには仮名テーブルのファイルがutf-8にも対応している必要があります。

**Comment by mtgto** [comment]
要望ありがとうございます。

設定ファイルの形式でずっと一人で悩んでいるままだったので、これを機にひとまず仮のファイルフォーマットでもいいから作ってみようかな…

### プラン1: JSON

機械は読み易いけど人間は書きづらい。コメントもつけづらい。

```json
{
  "!": "！",
  "z(": "（",
  "z ": "　"
}
```

### プラン2: AquaSKKのkana-rule.conf形式

実質は4カラムのCSVぽいけど半角スペースも使える。
入力、ひらがなモード時、カタカナモード時、半角カナモード時の変換を一行ごとに書く。
おそらく `#` で始まる行はコメントあつかい。

```ini
!,！,！,!
z ,　,　,　
```

### その他プラン

- YAML: macOSの標準APIで読めない
- TOML: 同上
- S式: 同上
- ini: スペースのとりあつかいとかちょっとややこしいかも?

----

AquaSKKと同じkana-rule.conf形式でとりあえず実装して将来変えたくなったら変える、でいこうかな。

**Comment by mtgto** [comment]
[v0.16.0](https://github.com/mtgto/macSKK/releases/tag/0.16.0) でユースケースにある2つは設定可能にしました。
使い方は [READMEのローマ字変換ルールの変更](https://github.com/mtgto/macSKK#%E3%83%AD%E3%83%BC%E3%83%9E%E5%AD%97%E5%A4%89%E6%8F%9B%E3%83%AB%E3%83%BC%E3%83%AB%E3%81%AE%E5%A4%89%E6%9B%B4) を参照してください。

細かい不具合などもし見つけていただけたらこのIssueや新しいIssueなどで教えていただければ幸いです。

**Comment by 4513ECHO** [comment]
ありがとうございます！
