### ISSUE TITLE
エラー報告:SKK-JISYO.L の読み込みでエラーが発生しました

### ISSUE THREAD

**Issue by pgary3** [mtgto/macSKK#97]
0.15.1にアップデートして、以下の2行の読み込みエラーが出るようになりました。
[2024-01-16 20:44:25.611] [error] 辞書 SKK-JISYO.L の読み込みで 38112行目で読み込みエラーが発生しました
[2024-01-16 20:44:25.611] [error] 辞書 SKK-JISYO.L の読み込みで 38113行目で読み込みエラーが発生しました
以下の2行のようです。
38112 sars-cov /severe acute respiratory syndrome coronavirus/SARSコロナウイルス
38113 sars-cov-2 /severe acute respiratory syndrome coronavirus 2/2019新型コロナウイルス
よろしくお願いいたします。

**Comment by mtgto** [comment]
報告ありがとうございます。
原因としてはSKK-JISYO.Lの38112行目と38113行目の末尾にスラッシュがないためなんですが、
v0.15.1で入れた修正でエラーを表示する修正を入れたため目立ってしまっています。
この2行だけ読めてないだけで他の行は読めているためあまり気にしないでいただいて大丈夫です。

SKK-JISYO.Lの最新ではこの問題は修正されているので、macSKKの次のバージョンでは修正版のSKK-JISYO.Lを同梱する予定です。
もし気になるようでしたら、 https://skk-dev.github.io/dict/ から SKK-JISYO.L.gz をダウンロードしてさしかえてもらうとエラーは表示されなくなると思います。

**Comment by pgary3** [comment]
ご検討、ご教示いただきありがとうございます。
SKK-JISYO.L の問題だったのですね。確かにその2行はスラッシュが抜けていました。
辞書の内容を確認したときに気づけませんでした。
取り急ぎ、SKK-JISYO.Lを差し替えて使用させていただきます。
ありがとうございました。

**Comment by mtgto** [comment]
[v0.16.0](https://github.com/mtgto/macSKK/releases/tag/0.16.0) からは修正版のSKK-JISYO.L辞書を同梱するようにしました。
またログ書式も少し修正し、読み込めない行があったときはその行をスキップするだけというのがわかるようにしました。

- v0.16.0以前: `辞書 SKK-JISYO.L の読み込みで XXXX行目で読み込みエラーが発生しました`
- v0.16.0以降: `辞書 SKK-JISYO.L の読み込みで XXXX行目を正常に読み込めなかったためこの行をスキップします`
